ignore-paths:
    - doc
    - cli.py
    - test
    - alembic
    - app_context_rqworker.py
    - warm.py
    - run.py
    - settings_local.py
    - update.py
pylint:
    disable:
        - no-name-in-module
        - unable-to-import
        - unused-argument
        - cyclic-import
        - unused-wildcard-impor
        - anomalous-backslash-in-string
        - no-member
    options:
        dummy-variables-rgx: _|dummy
